version: "3.8"
services:
  api-gateway:
    build: https://github.com/lawalletio/api-gateway.git
    image: lawallet/api-gateway
    container_name: api-gateway
    restart: always
    ports:
      - 3000:3000
    healthcheck:
      test: ["CMD-SHELL", "wget http://localhost:3000/health -q -O - > /dev/null"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 360s
    environment:
      MODULE_NAME: api-gateway
      DEBUG: ndk:*,api-gateway:*
      PORT: 3000
      NODE_ENV: production
      NOSTR_RELAYS: ws://nostream:8008
      NOSTR_WRITE_RELAY: ws://nostream:8008
      URLX_URI: http://urlx:3000
      CARD_URI: http://card:3000
      LEDGER_PUBLIC_KEY: ${LEDGER_PUBLIC_KEY}
      MINTER_PUBLIC_KEY: ${URLX_PUBLIC_KEY}
      URLX_PUBLIC_KEY: ${URLX_PUBLIC_KEY}
    depends_on:
      nostream:
        condition: service_healthy
