services:
  nostream:
    image: lawallet/nostream
    environment:
      DEBUG: '*'
      RELAY_PORT: 8008
      # Master
      NOSTR_CONFIG_DIR: /home/node/.nostr
      DB_HOST: nostream-db
      DB_PORT: 5432
      DB_USER: nostr_ts_relay
      DB_PASSWORD: nostr_ts_relay
      DB_NAME: nostr_ts_relay
      DB_MIN_POOL_SIZE: 16
      DB_MAX_POOL_SIZE: 64
      DB_ACQUIRE_CONNECTION_TIMEOUT: 60000
      # Read Replica
      READ_REPLICAS: 1
      READ_REPLICA_ENABLED: 'false'
      # Redis
      REDIS_HOST: nostream-cache
      REDIS_PORT: 6379
      REDIS_USER: default
      REDIS_PASSWORD: nostr_ts_relay
      TOR_HOST: tor_proxy
      TOR_CONTROL_PORT: 9051
      TOR_PASSWORD: nostr_ts_relay
      HIDDEN_SERVICE_PORT: 80
      # Nostream
      SECRET: ${NOSTREAM_SECRET}
    user: node:node
    volumes:
      - .nostr:/home/node/.nostr
    ports:
      - ${NOSTREAM_PORTS}
    depends_on:
      nostream-cache:
        condition: service_healthy
      nostream-db:
        condition: service_healthy
      nostream-migrate:
        condition: service_completed_successfully
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "wget http://localhost:8008/healthz -q -O - > /dev/null"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 360s
    networks:
      default:
  nostream-db:
    image: postgres
    environment:
      POSTGRES_DB: nostr_ts_relay
      POSTGRES_USER: nostr_ts_relay
      POSTGRES_PASSWORD: nostr_ts_relay
    volumes:
      - ${NOSTREAM_DOCKER_BASE}/.nostr/data:/var/lib/postgresql/data
      - ${NOSTREAM_DOCKER_BASE}/.nostr/db-logs:/var/log/postgresql
      - ${NOSTREAM_DOCKER_BASE}/postgresql.conf:/postgresql.conf:ro
    networks:
      default:
    command: postgres -c 'config_file=/postgresql.conf'
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nostr_ts_relay"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 360s
  nostream-cache:
    image: redis:7.0.5-alpine3.16
    volumes:
      - nostream-cache:/data
    command: redis-server --loglevel warning --requirepass nostr_ts_relay
    networks:
      default:
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "ping", "|", "grep", "PONG" ]
      interval: 1s
      timeout: 5s
      retries: 5
  nostream-migrate:
    image: node:18-alpine3.16
    environment:
      DB_HOST: nostream-db
      DB_PORT: 5432
      DB_USER: nostr_ts_relay
      DB_PASSWORD: nostr_ts_relay
      DB_NAME: nostr_ts_relay
    entrypoint: [ 'sh', '-c', 'cd code && npm install --no-save --quiet knex@2.4.0 pg@8.8.0 && npx knex migrate:latest' ]
    volumes:
      - ${NOSTREAM_DOCKER_BASE}/migrations:/code/migrations:ro
      - ${NOSTREAM_DOCKER_BASE}/knexfile.js:/code/knexfile.js
    depends_on:
      nostream-db:
        condition: service_healthy
    networks:
      default:

volumes:
  nostream-cache:
    driver: local
