version: "3.8"
services:
  urlx:
    image: lawallet/urlx
    container_name: urlx
    env_file:
      - ./.env
    environment:
      NODE_ENV: production
      REDIS_URI: redis://urlx-cache:6379
      NOSTR_RELAYS: ws://nostream:8008
    depends_on:
      urlx-cache:
        condition: service_started
      nostream:
        condition: service_healthy
  urlx-cache:
    image: redis:7-alpine
    container_name: urlx-cache
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1
    volumes:
      - urlx-cache:/data
volumes:
  urlx-cache:
    driver: local
