version: "3.8"
services:
  urlx:
    build: https://github.com/lawalletio/urlx.git
    image: lawallet/urlx
    restart: always
    ports:
      - ${URLX_PORTS}
    environment:
      MODULE_NAME: urlx
      DEBUG: ndk:*,urlx:*
      PORT: 3000
      NODE_ENV: production
      REDIS_URI: redis://urlx-cache:6379
      NOSTR_RELAYS: ws://nostream:8008
      NOSTR_WRITE_RELAY: ws://nostream:8008
      NOSTR_PRIVATE_KEY: ${URLX_PRIVATE_KEY}
      NOSTR_PUBLIC_KEY: ${URLX_PUBLIC_KEY}
      LEDGER_PUBLIC_KEY: ${LEDGER_PUBLIC_KEY}
      LNDCONNECT_URI: ${LNDCONNECT_URI}
      NODE_PUBKEY: ${NODE_PUBKEY}
      ACCEPTED_BASE_FEE: ${ACCEPTED_BASE_FEE}
      ACCEPTED_FEE_PERCENT: ${ACCEPTED_FEE_PERCENT}
    depends_on:
      urlx-cache:
        condition: service_started
      nostream:
        condition: service_healthy
  urlx-cache:
    image: redis:7-alpine
    restart: always
    ports:
      - ${URLX_CACHE_PORTS}
    command: redis-server --save 20 1
    volumes:
      - urlx-cache:/data

volumes:
  urlx-cache:
    driver: local
