version: "3.8"
services:
  urlx:
    image: lawallet/urlx
    container_name: urlx
    environment:
      MODULE_NAME: urlx
      DEBUG: ndk:*,urlx:*
      PORT: 3000
      NODE_ENV: production
      REDIS_URI: redis://urlx-cache:6379
      NOSTR_RELAYS: ws://nostream:8008
      NOSTR_PRIVATE_KEY: ${URLX_PRIVATE_KEY}
      NOSTR_PUBLIC_KEY: ${URLX_PUBLIC_KEY}
      LEDGER_PUBLIC_KEY: ${LEDGER_PUBLIC_KEY}
      LNDCONNECT_URI: lndconnect://polar-n1-alice:10009?cert=MIICJTCCAcygAwIBAgIQYsjTYLXZ3TlOGP-6nkWQRzAKBggqhkjOPQQDAjAxMR8wHQYDVQQKExZsbmQgYXV0b2dlbmVyYXRlZCBjZXJ0MQ4wDAYDVQQDEwVhbGljZTAeFw0yMzEwMDMxMzQ0MjRaFw0yNDExMjcxMzQ0MjRaMDExHzAdBgNVBAoTFmxuZCBhdXRvZ2VuZXJhdGVkIGNlcnQxDjAMBgNVBAMTBWFsaWNlMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEaKBuBcOUGcZ4_bXAOyZLGDA9qiDO0JVVbRkxQQ3LTKc26nPIHpnNVLWQi2Ceoq9yYDWocPuaz7_Di_WleKHpHqOBxTCBwjAOBgNVHQ8BAf8EBAMCAqQwEwYDVR0lBAwwCgYIKwYBBQUHAwEwDwYDVR0TAQH_BAUwAwEB_zAdBgNVHQ4EFgQUWjiRSTru929KzFSIZhJTKJk-H_8wawYDVR0RBGQwYoIFYWxpY2WCCWxvY2FsaG9zdIIFYWxpY2WCDnBvbGFyLW4xLWFsaWNlggR1bml4ggp1bml4cGFja2V0ggdidWZjb25uhwR_AAABhxAAAAAAAAAAAAAAAAAAAAABhwSsEwACMAoGCCqGSM49BAMCA0cAMEQCIGcHJHvwiHacxOrXaSzEZ3uVNwCxxuRlIdHR34VtawFqAiAMM6hfTVJBrwG9IgL1xxmfJeIycesjOT2L7rsX3Viifw&macaroon=AgEDbG5kAvgBAwoQLk6e1sY-US72nSYGoU3gVhIBMBoWCgdhZGRyZXNzEgRyZWFkEgV3cml0ZRoTCgRpbmZvEgRyZWFkEgV3cml0ZRoXCghpbnZvaWNlcxIEcmVhZBIFd3JpdGUaIQoIbWFjYXJvb24SCGdlbmVyYXRlEgRyZWFkEgV3cml0ZRoWCgdtZXNzYWdlEgRyZWFkEgV3cml0ZRoXCghvZmZjaGFpbhIEcmVhZBIFd3JpdGUaFgoHb25jaGFpbhIEcmVhZBIFd3JpdGUaFAoFcGVlcnMSBHJlYWQSBXdyaXRlGhgKBnNpZ25lchIIZ2VuZXJhdGUSBHJlYWQAAAYgBEQ_wwds7laXkvAmTndP5__mR3D_g0GJ0bq12SO3gFw
    depends_on:
      urlx-cache:
        condition: service_started
      nostream:
        condition: service_healthy
  urlx-cache:
    image: redis:7-alpine
    container_name: urlx-cache
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1
    volumes:
      - urlx-cache:/data
volumes:
  urlx-cache:
    driver: local
