include:
  - ./api-gateway/docker-compose.yaml
  - ./card/docker-compose.yaml
  - ./ledger/docker-compose.yaml
  - ./nostream/docker-compose.yaml
  - ./urlx/docker-compose.yaml

networks:
  default:
    name: lawallet
    ipam:
      driver: default
      config:
        - subnet: 10.10.10.0/24
