services:
  proxy:
    image: nginx:1.19.10-alpine
    ports:
      - 80
      - 443
    volumes:
      - ${PROXY_DOCKER_BASE}/nginx.conf:/etc/nginx/nginx.conf:ro
      - ${PROXY_DOCKER_BASE}/certs:/etc/nginx/certs:ro
    depends_on:
      api-gateway:
        condition: service_healthy
      nostream:
        condition: service_healthy
