version: "3.8"
services:
  monitor:
    build: https://github.com/lawalletio/monitor.git
    image: lawallet/monitor
    container_name: monitor
    restart: always
    ports:
      - 3003:3000
    environment:
      MODULE_NAME: monitor
      NODE_ENV: production
      NOSTR_RELAY: ws://nostream:8008
      PORT: 3000
      GATEWAY_PUBKEY: ${URLX_PUBLIC_KEY}
    depends_on:
      nostream:
        condition: service_healthy
    networks:
      - default
